esphome:
  name: luku-ir

esp32:
  board: esp32dev
  framework:
    type: arduino


external_components:
  - source:
      type: git
      url: https://github.com/lied/esphome-landisgyr
      ref: main
    components: [ sensor_meter_heating ]
    
sensor:
- platform: sensor_meter_heating
  lambda: |-
    auto my_sensor = new SensorMeterHeating();
    App.register_component(my_sensor);
    return {my_sensor->sensor_kWh, my_sensor->sensor_m3};

  sensors:
  - name: "Meter Heating MWh"
    unit_of_measurement: MWh
    accuracy_decimals: 3
  - name: "Meter Heating m3"
    unit_of_measurement: m3
    accuracy_decimals: 2
